# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the project files into the container
COPY . .

# Install Poetry
RUN pip install poetry

# Install dependencies
RUN poetry install

# Run the training script
CMD ["poetry", "run", "python", "src/train.py"]
