# Use the official Python image from the Docker Hub
FROM python:3.12-slim

WORKDIR /app
COPY . /app

RUN pip install poetry
RUN poetry install

ARG ENTRYPOINT
ENV ENTRYPOINT=${ENTRYPOINT}


ENTRYPOINT ["sh", "-c", "poetry run python -m fakenewsdetection.$ENTRYPOINT"]

CMD ["--help"]
